/*
 * @(#) $(JCGO)/goclsp/vm/gnu/classpath/CustomProperties.java --
 * Template file for custom properties initialization.
 **
 * Project: JCGO (http://www.ivmaisoft.com/jcgo/)
 * Copyright (C) 2001-2010 Ivan Maidanski <ivmai@mail.ru>
 * Distributed under the Terms of GNU Classpath License.
 **
 * Not a part of GNU Classpath.
 */

package gnu.classpath;

/* Do not edit this file in its original location */

import java.util.Properties;

final class CustomProperties
{ /* Template class source file (not a part of GNU Classpath) */

 static void initCustomProps(Properties properties)
 {
  /* properties.setProperty(<prop1_name_str>, <prop1_value_str>); */
 }
}
